Add some features.
racket/datalog pull request #15
Opened 2021-12-06 04:23 UTC by NoahStoryM

This PR mainly makes the following changes:

1. Add `port` parameter to `read-theory` and `write-theory`.
2. Use `void?` instead of `void` to check the return value of `write-theory`.
3. Modify the definition of `datalog-literal-variables`, so that it can accept any number of `stx` and return the `variable`s that are not repeated in these `stx`s. In this way, the `head vars` of the `conditional clause` can accept multiple same `variable`s as parameters (see the test file `idpath.rkt`).

2021-12-06 14:25 UTC, jeapostrophe requested changes

2021-12-06 14:25 UTC, jeapostrophe commented on serialize.rkt
> +(define (write-theory t [out (current-output-port)])
In my opinion, this is unnecessarily complicated. There is already `(parameterize ([current-output-port ...]) (f x))` so there's no reason to thread the port argument through all such `f`s

2021-12-06 14:25 UTC, jeapostrophe commented on stx.rkt
> -  (syntax-parse
The reformatting makes this patch hard to evaluate. Are these changed in some way?

2021-12-06 14:53 UTC, NoahStoryM commented on serialize.rkt
> +(define (write-theory t [out (current-output-port)])
It is true that the same function can be achieved through `current-output-port`, but I think it would be better to add the port parameter? At least for me, I rarely use parameterize just to pass parameters.

2021-12-06 14:53 UTC, NoahStoryM commented on stx.rkt
> -  (syntax-parse
Except for using `datalog-variable-symbol?` instead of `datalog-variable-string?`, the rest of `stx.rkt` doesn't be changed.

2022-03-31 08:25 UTC, NoahStoryM commented
Hi @jeapostrophe, I reformatted the `stx.rkt` file, does it looks better now?

Regarding the port argument, I think that IO-related functions in Racket (such as `print`, `pretty-print`, etc.) generally have such a port argument, and I hope that `read-theory` and `write-theory` can be more in line with these IO functions. And I think for some Racket programmers (including me), rather than frequently modifying the `current-port`, they may prefer to pass port as function argument. 

Of course, this is just my personal habits. If you feel that this modification complicates the problem, I'm willing to undo these changes, thank you.

2022-03-31 13:15 UTC, jeapostrophe approved these changes

2022-03-31 13:15 UTC, merged

2022-03-31 13:15 UTC, jeapostrophe commented
Thank you!